Style/MethodDefParentheses:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Layout/LineLength:
  Max: 80
Style/FrozenStringLiteralComment:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
